name: mlp_bench
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=1.4.0
  - aiohttp=3.8.4
  - aiosignal=1.3.1
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - attrs=23.1.0
  - blas=2.116
  - blas-devel=3.9.0
  - blinker=1.6.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.5.7
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.3.1
  - certifi=2023.5.7
  - cffi=1.15.1
  - charset-normalizer=3.2.0
  - chex=0.1.81
  - click=8.1.4
  - contourpy=1.1.0
  - cryptography=41.0.1
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvcc=12.2.91
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cuda-version=11.8
  - cudatoolkit=11.8.0
  - cudnn=8.8.0.121
  - cycler=0.11.0
  - dm-tree=0.1.7
  - ffmpeg=4.3
  - filelock=3.12.2
  - flatbuffers=22.12.06
  - flax=0.6.1
  - fonttools=4.40.0
  - freetype=2.12.1
  - frozenlist=1.3.3
  - gast=0.4.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.13
  - google-auth=2.17.3
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - grpcio=1.51.1
  - h5py=3.9.0
  - hdf5=1.14.1
  - icu=70.1
  - idna=3.4
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - jax=0.4.4
  - jaxlib=0.4.3
  - jinja2=3.1.2
  - jpeg=9e
  - keras=2.11.0
  - keras-preprocessing=1.1.2
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20220623.0
  - libaec=1.0.6
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.7.0.149
  - libcurand=10.3.3.53
  - libcurl=8.1.2
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=13.1.0
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - libgomp=13.1.0
  - libgrpc=1.51.1
  - libhwloc=2.9.1
  - libiconv=1.17
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnghttp2=1.52.0
  - libnpp=11.8.0.86
  - libnsl=2.0.0
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libprotobuf=3.21.12
  - libsqlite=3.42.0
  - libssh2=1.11.0
  - libstdcxx-ng=13.1.0
  - libtiff=4.5.0
  - libuuid=2.38.1
  - libwebp-base=1.3.1
  - libxcb=1.13
  - libxml2=2.10.3
  - libzlib=1.2.13
  - llvm-openmp=16.0.6
  - markdown=3.4.3
  - markdown-it-py=3.0.0
  - markupsafe=2.1.3
  - matplotlib-base=3.7.2
  - mdurl=0.1.0
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - ml_dtypes=0.2.0
  - mpc=1.3.1
  - mpfr=4.2.0
  - mpmath=1.3.0
  - msgpack-python=1.0.5
  - multidict=6.0.4
  - munkres=1.1.4
  - nccl=2.18.3.1
  - ncurses=6.4
  - nettle=3.6
  - networkx=3.1
  - numpy=1.25.1
  - oauthlib=3.2.2
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openssl=3.1.1
  - opt_einsum=3.3.0
  - optax=0.1.5
  - packaging=23.1
  - pillow=9.4.0
  - pip=23.1.2
  - platformdirs=3.8.1
  - pooch=1.7.0
  - protobuf=4.21.12
  - pthread-stubs=0.4
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pygments=2.15.1
  - pyjwt=2.7.0
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.10.12
  - python-dateutil=2.8.2
  - python-flatbuffers=23.5.26
  - python_abi=3.10
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyu2f=0.1.5
  - pyyaml=6.0
  - re2=2023.02.01
  - readline=8.2
  - requests=2.31.0
  - requests-oauthlib=1.3.1
  - rich=13.4.2
  - rsa=4.9
  - scipy=1.11.1
  - setuptools=68.0.0
  - six=1.16.0
  - snappy=1.1.10
  - sympy=1.12
  - tbb=2021.9.0
  - tensorboard=2.11.2
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.11.0
  - tensorflow-base=2.11.0
  - tensorflow-estimator=2.11.0
  - termcolor=2.3.0
  - tk=8.6.12
  - toolz=0.12.0
  - torchaudio=2.0.2
  - torchtriton=2.0.0
  - torchvision=0.15.2
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzdata=2023c
  - unicodedata2=15.0.0
  - urllib3=2.0.3
  - werkzeug=2.3.6
  - wheel=0.40.0
  - wrapt=1.15.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.2
  - zipp=3.16.0
  - zlib=1.2.13
  - zstd=1.5.2
